In [2]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [3]:
import os

print(os.getcwd())

d:\AI_Projects\Projects\ANN_Classification

In [4]:
print(os.listdir())

['Churn_Modelling.csv', 'experiments.ipynb', 'label_encoder_gender.pkl', 'logs', 'model.h5', 'onehot_encoder_geo.pkl', 'prediction.ipynb', 'requirements.txt', 'scaler.pkl']

In [5]:
import os

print("Current Directory:", os.getcwd())
print("File Exists:", os.path.exists("onehot_encoder_geo.pkl"))
print("Files:", os.listdir())

Current Directory: d:\AI_Projects\Projects\ANN_Classification
File Exists: True
Files: ['Churn_Modelling.csv', 'experiments.ipynb', 'label_encoder_gender.pkl', 'logs', 'model.h5', 'onehot_encoder_geo.pkl', 'prediction.ipynb', 'requirements.txt', 'scaler.pkl']

In [18]:
import pickle
from tensorflow.keras.models import load_model

model = load_model('model.h5')

with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder_geo = pickle.load(file)

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [19]:
print(type(onehot_encoder_geo))
print(type(label_encoder_gender))
print(type(scaler))

<class 'sklearn.preprocessing._encoders.OneHotEncoder'>
<class 'sklearn.preprocessing._label.LabelEncoder'>
<class 'sklearn.preprocessing._data.StandardScaler'>

In [20]:
input_data = {
  'CreditScore':600,
  'Geography':'France',
  'Gender':'Male',
  'Age':40,
  'Tenure':3,
  'Balance':60000,
  'NumOfProducts':2,
  'HasCrCard':1,
  'IsActiveMember':1,
  'EstimatedSalary':50000

}

In [21]:
##One hot encode the Geography
geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

d:\AI_Projects\Environments\dl-env\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [22]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [23]:
###Encode my categorical variables
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [24]:
##Concatenation on one hot encoded data
input_df=pd.concat([input_df.drop(columns=['Geography']),geo_encoded_df],axis = 1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [25]:
##Scaling thr input data
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [26]:
###Predict churn
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

array([[0.03978313]], dtype=float32)

In [27]:
prediction_proba = prediction[0][0]

In [28]:
prediction_proba

np.float32(0.039783128)

In [29]:
if prediction_proba > 0.5:
  print('The customer is likely to churn.')
else:
  print('The customer is not likely to churn')

The customer is not likely to churn

In [17]:
import os

print(os.listdir())

['app.py', 'Churn_Modelling.csv', 'experiments.ipynb', 'label_encoder_gender.pkl', 'logs', 'model.h5', 'onehot_encoder_geo.pkl', 'prediction.ipynb', 'requirements.txt', 'scaler.pkl']